name = "bare_complex_drivers"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[configuration.variables]
eth = { type = "Enum", values = ["yes", "no"], default = "yes" }
framebuffer_ltdc = { type = "Enum", values = ["yes", "no"], default = "yes" }
dma2d_bitmap = { type = "Enum", values = ["yes", "no"], default = "yes" }
bitmap = { type = "Enum", values = ["yes", "no"], default = "yes" }

[[depends-on]]
bare_types = "0.1.0-dev"
bare_hal = "0.1.0-dev"
bare_drivers = "0.1.0-dev"
bare_devices = "0.1.0-dev"